### ISSUE TITLE
CAPTCHA

### ISSUE THREAD

**Issue by mgronseth** [aaroads-wiki/aaroads-config#16]
https://www.mediawiki.org/wiki/Extension:ConfirmEdit to add CAPTCHA. 

https://www.mediawiki.org/wiki/Extension:QuestyCaptcha is a plugin for that that looks like the best option to use questions instead of images. 

https://www.mediawiki.org/wiki/Extension:QuestyCaptchaEditor adds a page to edit the questions from within the wiki itself.

**Comment by rschen7754** [comment]
The editor requires hacks to core MW code. Not a fan of that :(

**Comment by rschen7754** [comment]
Done otherwise
