### ISSUE TITLE
OAuth

### ISSUE THREAD

**Issue by timboehde** [aaroads-wiki/aaroads-config#17]
https://www.mediawiki.org/wiki/Extension:OAuth

For integrating with InternetArchiveBot

**Comment by mgronseth** [comment]
"DB access is optional, but helpful." is the other comment on IAB supporting our wiki.

**Comment by rschen7754** [comment]
Now done, rights were left for crats:


```
$wgGroupPermissions['bureaucrat']['mwoauthproposeconsumer'] = true;
$wgGroupPermissions['bureaucrat']['mwoauthupdateownconsumer'] = true;
$wgGroupPermissions['bureaucrat']['mwoauthmanageconsumer'] = true;
$wgGroupPermissions['bureaucrat']['mwoauthsuppress'] = true;
$wgGroupPermissions['bureaucrat']['mwoauthviewprivate'] = true;
$wgGroupPermissions['bureaucrat']['mwoauthmanagemygrants'] = true;

```

**Comment by rschen7754** [comment]
$wgGroupPermissions['user']['mwoauthproposeconsumer'] = true;
$wgGroupPermissions['user]['mwoauthupdateownconsumer'] = true;

Matches what Meta has
