### ISSUE TITLE
Autoconfirmed and account creation

### ISSUE THREAD

**Issue by mgronseth** [aaroads-wiki/aaroads-config#18]
https://www.mediawiki.org/wiki/Manual:Autoconfirmed_users discusses how to configure the settings for auto confirmed. Both conditions set have to be met, so 4 days _and_ 10 edits, not 4 days or 10 edits. 

https://www.mediawiki.org/wiki/Manual:Preventing_access#Restrict_creating_of_all_pages then has the details on how to prevent article creation.

**Comment by rschen7754** [comment]
Group created, 4 days/10 edits

**Comment by rschen7754** [comment]
$wgGroupPermissions['user']['createpage'] = false;
$wgGroupPermissions['autoconfirmed']['createpage'] = true;

Might be an issue with new users creating userpages

**Comment by rschen7754** [comment]
Undone because it was blocking users creating userpages
