### ISSUE TITLE
Ensure OSM credit is visible on mobile

### ISSUE THREAD

**Issue by zyphlar** [aaroads-wiki/aaroads-config#19]
![Screenshot_20230907_163215_Firefox](https://github.com/aaroads-wiki/aaroads-config/assets/48434/5fdfe8d0-6deb-4649-a9b4-a7faa2943f09)

It's important for licensing that a mobile user be able to see OSM somewhere, but the current viewport cuts it off

**Comment by 1ec5** [comment]
https://wiki.aaroads.com/wiki/Special:Diff/163420 switches to MapLibre’s non-compact attribution style. Does this work better in a mobile browser?

**Comment by zyphlar** [comment]
Looking good!
