### ISSUE TITLE
JWB hasn't worked since Sept. 5

### ISSUE THREAD

**Issue by timboehde** [aaroads-wiki/aaroads-config#21]
Not sure what changed on or around Sept. 5–6, but I can no longer get to JWB. https://wiki.aaroads.com/wiki/AARoads:AutoWikiBrowser/Script should open the JWB interface, but it just sits there.

**Comment by rschen7754** [comment]
Likely a wiki-side issue

mw.loader.load('//wiki.aaroads.com/w/index.php?title=MediaWiki:AutoWikiBrowser/JWB.js/load.js&action=raw&ctype=text/javascript');
