### ISSUE TITLE
Configure skin to be mobile-friendly

### ISSUE THREAD

**Issue by Scott5114** [aaroads-wiki/aaroads-config#22]
We need to either investigate how to make the Vector theme responsive to mobile devices (I suspect this what the motivation for Vector 2 was) or switch to a mobile-friendly skin like Pivot.

This is something that affects Google PageRank.

**Comment by rschen7754** [comment]
https://www.mediawiki.org/wiki/Extension:MobileFrontend

**Comment by rschen7754** [comment]
Done, there may be issues with it
