### ISSUE TITLE
MassMessage

### ISSUE THREAD

**Issue by rschen7754** [aaroads-wiki/aaroads-config#25]
Or some sort of newsletter extension

**Comment by mgronseth** [comment]
MM is pretty easy, once I refreshed myself on how to use it.

**Comment by rschen7754** [comment]
https://www.mediawiki.org/wiki/Extension:MassMessage does not require DB.

https://www.mediawiki.org/wiki/Extension:Newsletter also exists, however since we will only have 1 newsletter (?) it seems overkill
