### ISSUE TITLE
Special pages time reset

### ISSUE THREAD

**Issue by timboehde** [aaroads-wiki/aaroads-config#55]
Can we change the times the Special pages (WantedCategories, WantedTemplates, etc.) generate? 04:00 and 16:00 Eastern Time is really inconvenient.

Either 00:00 and 12:00 Eastern Time if we keep at twice per day, or
00:00, 08:00, and 16:00 for three times per day, or
00:00, 06:00, 12:00, and 18:00 for four times per day

**Comment by rschen7754** [comment]
Done
